### ISSUE TITLE
while compiling rom giving error

### ISSUE THREAD

**Issue by MandySingh3** [CyanogenMod/android_hardware_samsung_slsi-cm_exynos5#1]
target  C++: libExynosHWCService <= hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp
target  C++: libExynosHWCService <= hardware/samsung_slsi-cm/exynos5/libhwcService/IExynosHWC.cpp
target  C: libexynosv4l2 <= hardware/samsung_slsi-cm/exynos/libv4l2/exynos_v4l2.c
target  C: libexynosv4l2 <= hardware/samsung_slsi-cm/exynos/libv4l2/exynos_subdev.c
In file included from hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:16:0:
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.h: In constructor 'android::ExynosHWCService::ExynosHWCService()':
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.h:122:67: warning: 'android::ExynosHWCService::bootFinishedCallback' will be initialized after [-Wreorder]
     void (_bootFinishedCallback)(exynos5_hwc_composer_device_1_t *);
                                                                   ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.h:113:40: warning:   'void (_ android::ExynosHWCService::doPSRExit)(ExynosHWCCtx_)' [-Wreorder]
     void (_doPSRExit)(ExynosHWCCtx _ctx);
                                        ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:39:1: warning:   when initialized here [-Wreorder]
 ExynosHWCService::ExynosHWCService() :
 ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp: At global scope:
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:60:59: warning: unused parameter 'disp_w' [-Wunused-parameter]
                                              unsigned int disp_w, unsigned int disp_h)
                                                           ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:60:80: warning: unused parameter 'disp_h' [-Wunused-parameter]
                                              unsigned int disp_w, unsigned int disp_h)
                                                                                ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:74:45: warning: unused parameter 'black' [-Wunused-parameter]
 void ExynosHWCService::setWFDSleepCtrl(bool black)
                                             ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp: In member function 'virtual void android::ExynosHWCService::setHdmiResolution(int, int)':
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:212:22: error: 'V4L2_DV_1080I60_SB_HALF' was not declared in this scope
         resolution = V4L2_DV_1080I60_SB_HALF;
                      ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:217:22: error: 'V4L2_DV_1080I59_94_SB_HALF' was not declared in this scope
         resolution = V4L2_DV_1080I59_94_SB_HALF;
                      ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp: At global scope:
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:243:53: warning: unused parameter 'channels' [-Wunused-parameter]
 void ExynosHWCService::setHdmiAudioChannel(uint32_t channels)
                                                     ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:276:45: warning: unused parameter 'fd1' [-Wunused-parameter]
 int ExynosHWCService::getWFDOutputInfo(int *fd1, int *fd2, struct wfd_layer_t *wfd_info)
                                             ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:276:55: warning: unused parameter 'fd2' [-Wunused-parameter]
 int ExynosHWCService::getWFDOutputInfo(int *fd1, int *fd2, struct wfd_layer_t *wfd_info)
                                                       ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:276:80: warning: unused parameter 'wfd_info' [-Wunused-parameter]
 int ExynosHWCService::getWFDOutputInfo(int *fd1, int *fd2, struct wfd_layer_t *wfd_info)
                                                                                ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp: In member function 'virtual void android::ExynosHWCService::getHdmiResolution(uint32_t_, uint32_t_)':
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:293:10: error: 'V4L2_DV_480P59_94' was not declared in this scope
     case V4L2_DV_480P59_94:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:294:10: error: 'V4L2_DV_480P60' was not declared in this scope
     case V4L2_DV_480P60:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:298:10: error: 'V4L2_DV_576P50' was not declared in this scope
     case V4L2_DV_576P50:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:302:10: error: 'V4L2_DV_720P24' was not declared in this scope
     case V4L2_DV_720P24:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:303:10: error: 'V4L2_DV_720P25' was not declared in this scope
     case V4L2_DV_720P25:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:304:10: error: 'V4L2_DV_720P30' was not declared in this scope
     case V4L2_DV_720P30:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:305:10: error: 'V4L2_DV_720P50' was not declared in this scope
     case V4L2_DV_720P50:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:306:10: error: 'V4L2_DV_720P59_94' was not declared in this scope
     case V4L2_DV_720P59_94:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:307:10: error: 'V4L2_DV_720P60' was not declared in this scope
     case V4L2_DV_720P60:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:308:10: error: 'V4L2_DV_720P60_FP' was not declared in this scope
     case V4L2_DV_720P60_FP:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:309:10: error: 'V4L2_DV_720P60_SB_HALF' was not declared in this scope
     case V4L2_DV_720P60_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:310:10: error: 'V4L2_DV_720P60_TB' was not declared in this scope
     case V4L2_DV_720P60_TB:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:311:10: error: 'V4L2_DV_720P59_94_FP' was not declared in this scope
     case V4L2_DV_720P59_94_FP:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:312:10: error: 'V4L2_DV_720P59_94_SB_HALF' was not declared in this scope
     case V4L2_DV_720P59_94_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:313:10: error: 'V4L2_DV_720P59_94_TB' was not declared in this scope
     case V4L2_DV_720P59_94_TB:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:314:10: error: 'V4L2_DV_720P50_FP' was not declared in this scope
     case V4L2_DV_720P50_FP:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:315:10: error: 'V4L2_DV_720P50_SB_HALF' was not declared in this scope
     case V4L2_DV_720P50_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:316:10: error: 'V4L2_DV_720P50_TB' was not declared in this scope
     case V4L2_DV_720P50_TB:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:320:10: error: 'V4L2_DV_1080I29_97' was not declared in this scope
     case V4L2_DV_1080I29_97:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:321:10: error: 'V4L2_DV_1080I30' was not declared in this scope
     case V4L2_DV_1080I30:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:322:10: error: 'V4L2_DV_1080I25' was not declared in this scope
     case V4L2_DV_1080I25:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:323:10: error: 'V4L2_DV_1080I50' was not declared in this scope
     case V4L2_DV_1080I50:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:324:10: error: 'V4L2_DV_1080I60' was not declared in this scope
     case V4L2_DV_1080I60:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:325:10: error: 'V4L2_DV_1080P24' was not declared in this scope
     case V4L2_DV_1080P24:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:326:10: error: 'V4L2_DV_1080P25' was not declared in this scope
     case V4L2_DV_1080P25:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:327:10: error: 'V4L2_DV_1080P30' was not declared in this scope
     case V4L2_DV_1080P30:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:328:10: error: 'V4L2_DV_1080P50' was not declared in this scope
     case V4L2_DV_1080P50:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:330:10: error: 'V4L2_DV_1080I59_94' was not declared in this scope
     case V4L2_DV_1080I59_94:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:331:10: error: 'V4L2_DV_1080P59_94' was not declared in this scope
     case V4L2_DV_1080P59_94:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:332:10: error: 'V4L2_DV_1080P24_FP' was not declared in this scope
     case V4L2_DV_1080P24_FP:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:333:10: error: 'V4L2_DV_1080P24_SB_HALF' was not declared in this scope
     case V4L2_DV_1080P24_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:334:10: error: 'V4L2_DV_1080P24_TB' was not declared in this scope
     case V4L2_DV_1080P24_TB:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:335:10: error: 'V4L2_DV_1080P23_98_FP' was not declared in this scope
     case V4L2_DV_1080P23_98_FP:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:336:10: error: 'V4L2_DV_1080P23_98_SB_HALF' was not declared in this scope
     case V4L2_DV_1080P23_98_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:337:10: error: 'V4L2_DV_1080P23_98_TB' was not declared in this scope
     case V4L2_DV_1080P23_98_TB:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:338:10: error: 'V4L2_DV_1080I60_SB_HALF' was not declared in this scope
     case V4L2_DV_1080I60_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:339:10: error: 'V4L2_DV_1080I59_94_SB_HALF' was not declared in this scope
     case V4L2_DV_1080I59_94_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:340:10: error: 'V4L2_DV_1080I50_SB_HALF' was not declared in this scope
     case V4L2_DV_1080I50_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:341:10: error: 'V4L2_DV_1080P60_SB_HALF' was not declared in this scope
     case V4L2_DV_1080P60_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:342:10: error: 'V4L2_DV_1080P60_TB' was not declared in this scope
     case V4L2_DV_1080P60_TB:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:343:10: error: 'V4L2_DV_1080P30_FP' was not declared in this scope
     case V4L2_DV_1080P30_FP:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:344:10: error: 'V4L2_DV_1080P30_SB_HALF' was not declared in this scope
     case V4L2_DV_1080P30_SB_HALF:
          ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:345:10: error: 'V4L2_DV_1080P30_TB' was not declared in this scope
     case V4L2_DV_1080P30_TB:
          ^
build/core/binary.mk:730: recipe for target '/home/mandy/cm13/out/target/product/j7xeltexx/obj/SHARED_LIBRARIES/libExynosHWCService_intermediates/ExynosHWCService.o' failed
make: *_\* [/home/mandy/cm13/out/target/product/j7xeltexx/obj/SHARED_LIBRARIES/libExynosHWCService_intermediates/ExynosHWCService.o] Error 1
make: **\* Waiting for unfinished jobs....
hardware/samsung_slsi-cm/exynos5/libhwcService/IExynosHWC.cpp:365:32: warning: unused parameter 'ctrl' [-Wunused-parameter]
     virtual void setHWCCtl(int ctrl, int val) {
                                ^
hardware/samsung_slsi-cm/exynos5/libhwcService/IExynosHWC.cpp:365:42: warning: unused parameter 'val' [-Wunused-parameter]
     virtual void setHWCCtl(int ctrl, int val) {
                                          ^
hardware/samsung_slsi-cm/exynos/libv4l2/exynos_subdev.c: In function 'exynos_subdev_get_node_num':
hardware/samsung_slsi-cm/exynos/libv4l2/exynos_subdev.c:71:57: warning: unused parameter 'oflag' [-Wunused-parameter]
 int exynos_subdev_get_node_num(const char *devname, int oflag, ...)
                                                         ^

**Comment by MandySingh3** [comment]
nobody help

**Comment by Anks329** [comment]
What was the solution to this error?

**Comment by MandySingh3** [comment]
no one given answer
